-- MySQL Script generated by MySQL Workbench
-- Wed Apr 26 18:16:07 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Pizzeria
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Pizzeria` ;

-- -----------------------------------------------------
-- Schema Pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pizzeria` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `Pizzeria` ;

-- -----------------------------------------------------
-- Table `Pizzeria`.`Adreça`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`Adreça` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`Adreça` (
  `id_Adreça` INT NOT NULL AUTO_INCREMENT,
  `carrer` VARCHAR(15) NOT NULL,
  `numero` INT(11) NOT NULL,
  `pis` VARCHAR(3) NOT NULL,
  `codi_postal` INT(11) NOT NULL,
  `localitat` VARCHAR(20) NOT NULL,
  `provincia` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_Adreça`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Beguda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`Beguda` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`Beguda` (
  `id_Beguda` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(15) NOT NULL,
  `descripcio` TINYTEXT NOT NULL,
  `imatge` BLOB NOT NULL,
  `preu` DOUBLE NOT NULL,
  PRIMARY KEY (`id_Beguda`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Pizza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`Pizza` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`Pizza` (
  `id_Pizza` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(15) NOT NULL,
  `descripcio` TINYTEXT NOT NULL,
  `imatge` BLOB NOT NULL,
  `preu` DOUBLE NOT NULL,
  PRIMARY KEY (`id_Pizza`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Hamburguesa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`Hamburguesa` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`Hamburguesa` (
  `id_Hamburguesa` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(15) NOT NULL,
  `descripcio` TINYTEXT NOT NULL,
  `imatge` BLOB NOT NULL,
  `preu` DOUBLE NOT NULL,
  PRIMARY KEY (`id_Hamburguesa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Comanda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`Comanda` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`Comanda` (
  `id_Comanda` INT NOT NULL AUTO_INCREMENT,
  `data/hora` DATETIME NOT NULL,
  `lloc_recollida` CHAR(1) NOT NULL COMMENT 'Tipo de repartiment:\\nB = Botiga\\nD = Domicili',
  `quantitat_producte` INT NOT NULL,
  `preu` INT NOT NULL,
  `id_Pizza` INT NOT NULL,
  `id_Hamburguesa` INT NOT NULL,
  `id_Beguda` INT NOT NULL,
  PRIMARY KEY (`id_Comanda`),
  INDEX `fk_Pizza_idx` (`id_Pizza` ASC) VISIBLE,
  INDEX `fk_Hamburguesa1_idx` (`id_Hamburguesa` ASC) VISIBLE,
  INDEX `fk_Beguda1_idx` (`id_Beguda` ASC) VISIBLE,
  CONSTRAINT `fk_Pizza`
    FOREIGN KEY (`id_Pizza`)
    REFERENCES `Pizzeria`.`Pizza` (`id_Pizza`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hamburguesa1`
    FOREIGN KEY (`id_Hamburguesa`)
    REFERENCES `Pizzeria`.`Hamburguesa` (`id_Hamburguesa`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Beguda1`
    FOREIGN KEY (`id_Beguda`)
    REFERENCES `Pizzeria`.`Beguda` (`id_Beguda`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Botiga`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`Botiga` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`Botiga` (
  `id_Botiga` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(20) NOT NULL,
  `id_Comanda` INT NOT NULL,
  PRIMARY KEY (`id_Botiga`),
  INDEX `fk_Comanda1_idx` (`id_Comanda` ASC) VISIBLE,
  CONSTRAINT `fk_Comanda1`
    FOREIGN KEY (`id_Comanda`)
    REFERENCES `Pizzeria`.`Comanda` (`id_Comanda`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Categoria_Pizza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`Categoria_Pizza` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`Categoria_Pizza` (
  `id_Categoria_Pizza` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `id_Pizza` INT NOT NULL,
  PRIMARY KEY (`id_Categoria_Pizza`),
  INDEX `fk_Pizza1_idx` (`id_Pizza` ASC) VISIBLE,
  CONSTRAINT `fk_Pizza1`
    FOREIGN KEY (`id_Pizza`)
    REFERENCES `Pizzeria`.`Pizza` (`id_Pizza`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`Client` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`Client` (
  `id_Client` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(15) NOT NULL,
  `cognom_1` VARCHAR(15) NOT NULL COMMENT 'Primer cognom',
  `cognom_2` VARCHAR(15) NOT NULL COMMENT 'Segon cognom',
  `telefon` INT(11) NOT NULL,
  `id_Adreça` INT NOT NULL,
  `id_Comanda` INT NOT NULL,
  PRIMARY KEY (`id_Client`),
  INDEX `fk_Adreça1_idx` (`id_Adreça` ASC) VISIBLE,
  INDEX `fk_Comanda3_idx` (`id_Comanda` ASC) VISIBLE,
  CONSTRAINT `fk_Adreça1`
    FOREIGN KEY (`id_Adreça`)
    REFERENCES `Pizzeria`.`Adreça` (`id_Adreça`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comanda3`
    FOREIGN KEY (`id_Comanda`)
    REFERENCES `Pizzeria`.`Comanda` (`id_Comanda`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Cuiner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`Cuiner` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`Cuiner` (
  `id_Cuiner` INT NOT NULL,
  PRIMARY KEY (`id_Cuiner`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Empleat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`Empleat` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`Empleat` (
  `id_Empleat` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(15) NOT NULL,
  `cognom_1` VARCHAR(15) NOT NULL COMMENT 'Primer cognom',
  `cognom_2` VARCHAR(15) NOT NULL COMMENT 'Segon cognom',
  `telefon` INT(11) NOT NULL,
  `nif` VARCHAR(10) NOT NULL,
  `id_Cuiner` INT NOT NULL,
  PRIMARY KEY (`id_Empleat`),
  UNIQUE INDEX `nif_UNIQUE` (`nif` ASC) VISIBLE,
  INDEX `fk_Cuiner1_idx` (`id_Cuiner` ASC) VISIBLE,
  CONSTRAINT `fk_Cuiner1`
    FOREIGN KEY (`id_Cuiner`)
    REFERENCES `Pizzeria`.`Cuiner` (`id_Cuiner`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Repartidor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`Repartidor` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`Repartidor` (
  `id_Repartidor` INT NOT NULL,
  `entrega` DATETIME NOT NULL COMMENT 'Data i hora en l\'entrega de la comanda',
  `id_Comanda` INT NOT NULL,
  `id_Empleat` INT(11) NOT NULL,
  PRIMARY KEY (`id_Repartidor`),
  INDEX `fk_Comanda2_idx` (`id_Comanda` ASC) VISIBLE,
  INDEX `fk_Empleat1_idx` (`id_Empleat` ASC) VISIBLE,
  CONSTRAINT `fk_Comanda2`
    FOREIGN KEY (`id_Comanda`)
    REFERENCES `Pizzeria`.`Comanda` (`id_Comanda`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleat1`
    FOREIGN KEY (`id_Empleat`)
    REFERENCES `Pizzeria`.`Empleat` (`id_Empleat`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
